FROM php:8.1-apache

# set your user name, ex: user=bernardo
ARG user=edu
ARG uid=1000

RUN docker-php-ext-install pdo pdo_mysql

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

COPY . /var/www/html

# Set working directory
WORKDIR /var/www/html

EXPOSE 80

USER $user